using Microsoft.CodeAnalysis;

namespace RuniOS.CodeAnalysis.Generators.TypeRegistry;

/// <summary>
/// Injects the internal registry marker attribute definitions used by the type registry generators.<br/>
/// 타입 레지스트리 생성기가 사용하는 내부 레지스트리 표식 특성 정의를 주입합니다.
/// </summary>
[Generator]
public sealed class GenerateAttributedTypeRegistryAttributeSourceGenerator : IIncrementalGenerator
{
    const string source =
        """
        // <auto-generated/>
        // ReSharper disable All
        #nullable enable
        namespace RuniOS.Reflection
        {
            /// <summary>
            /// Marks an attribute-based type registry property. When no base type is supplied, the declaring type is used.<br/>
            /// 특성 기반 타입 레지스트리 속성을 표시합니다. 기본 타입을 지정하지 않으면 선언 타입을 사용합니다.
            /// </summary>
            [global::System.Runtime.CompilerServices.CompilerGenerated]
            [global::Microsoft.CodeAnalysis.Embedded]
            sealed class GenerateAttributedTypeRegistryAttribute : GenerateTypeRegistryAttribute
            {
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public global::System.Type? baseType { get; }

                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public GenerateAttributedTypeRegistryAttribute() => baseType = null;

                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public GenerateAttributedTypeRegistryAttribute(global::System.Type baseType) => this.baseType = baseType;
            }
        }
        """;

    /// <summary>
    /// Adds the generated registry marker attribute definitions to the compilation.<br/>
    /// 생성된 레지스트리 표식 특성 정의를 컴파일에 추가합니다.
    /// </summary>
    /// <param name="context">
    /// The incremental generator initialization context receiving the post-initialization output callback.<br/>
    /// 초기화 후 출력 콜백을 받을 증분 생성기 초기화 컨텍스트입니다.
    /// </param>
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(static context => context.AddSource("RuniOS.Reflection.GenerateTypeRegistryAttribute.g.cs", source));
}
