using Microsoft.CodeAnalysis;

namespace RuniOS.CodeAnalysis.Generators.TypeRegistry;

/// <summary>
/// Injects the internal registry marker attribute definitions used by the type registry generators.<br/>
/// 타입 레지스트리 생성기가 사용하는 내부 레지스트리 표식 특성 정의를 주입합니다.
/// </summary>
[Generator]
public sealed class GenerateAssignableTypeRegistryAttributeSourceGenerator : IIncrementalGenerator
{
    const string source =
        """
        // <auto-generated/>
        // ReSharper disable All
        #nullable enable
        namespace RuniOS.Reflection
        {
            /// <summary>
            /// Marks an assignable type registry property.<br/>
            /// 할당 가능한 타입 레지스트리 속성을 표시합니다.
            /// </summary>
            [global::System.Runtime.CompilerServices.CompilerGenerated]
            [global::Microsoft.CodeAnalysis.Embedded]
            sealed class GenerateAssignableTypeRegistryAttribute : GenerateTypeRegistryAttribute
            {
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public bool requireDefaultConstructor { get; }

                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public global::System.Type[] baseTypes { get; }

                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public GenerateAssignableTypeRegistryAttribute(params global::System.Type[] baseTypes) => this.baseTypes = baseTypes;

                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public GenerateAssignableTypeRegistryAttribute(bool requireDefaultConstructor, params global::System.Type[] baseTypes)
                {
                    this.requireDefaultConstructor = requireDefaultConstructor;
                    this.baseTypes = baseTypes;
                }
            }
        }
        """;

    /// <summary>
    /// Adds the generated registry marker attribute definitions to the compilation.<br/>
    /// 생성된 레지스트리 표식 특성 정의를 컴파일에 추가합니다.
    /// </summary>
    /// <param name="context">
    /// The incremental generator initialization context receiving the post-initialization output callback.<br/>
    /// 초기화 후 출력 콜백을 받을 증분 생성기 초기화 컨텍스트입니다.
    /// </param>
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(static context => context.AddSource("RuniOS.Reflection.GenerateTypeRegistryAttribute.g.cs", source));
}
