using Microsoft.CodeAnalysis;

namespace RuniOS.CodeAnalysis.Generators.TypeRegistry;

/// <summary>
/// Injects the internal attribute definition used to mark registry properties for generation.<br/>
/// 레지스트리 속성을 생성 대상으로 표시하는 내부 특성 정의를 주입합니다.
/// </summary>
[Generator]
public sealed class GenerateTypeRegistryAttributeSourceGenerator : IIncrementalGenerator
{
    const string source =
        """
        // <auto-generated/>
        // ReSharper disable All
        #nullable enable
        namespace RuniOS.Reflection
        {
            /// <summary>
            /// Marks a property whose type registry implementation should be generated.<br/>
            /// 타입 레지스트리 구현을 생성할 속성을 표시합니다.
            /// </summary>
            // TypeRegistrySourceGenerator가 Property 대상의 이 정확한 메타데이터 이름을 찾습니다.
            [global::System.Runtime.CompilerServices.CompilerGenerated]
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
            sealed class GenerateTypeRegistryAttribute : global::System.Attribute { }
        }
        """;

    /// <summary>
    /// Adds the generated <c>GenerateTypeRegistryAttribute</c> definition to the compilation.<br/>
    /// 생성된 <c>GenerateTypeRegistryAttribute</c> 정의를 컴파일에 추가합니다.
    /// </summary>
    /// <param name="context">
    /// The incremental generator initialization context receiving the post-initialization output callback.<br/>
    /// 초기화 후 출력 콜백을 받을 증분 생성기 초기화 컨텍스트입니다.
    /// </param>
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(static context => context.AddSource("RuniOS.Reflection.GenerateTypeRegistryAttribute.g.cs", source));
}
