using Microsoft.CodeAnalysis;

namespace RuniOS.CodeAnalysis.Generators.TypeRegistry;

/// <summary>
/// Injects the internal assembly attribute used to restore registry properties from referenced assemblies.<br/>
/// 참조된 어셈블리에서 레지스트리 속성을 복원하는 내부 어셈블리 특성 정의를 주입합니다.
/// </summary>
[Generator]
public sealed class TypeRegistryManifestAttributeSourceGenerator : IIncrementalGenerator
{
    const string source =
        """
        // <auto-generated/>
        // ReSharper disable All
        #nullable enable
        namespace RuniOS.Reflection
        {
            /// <summary>
            /// Identifies a registry property that was generated in another assembly.<br/>
            /// 다른 어셈블리에서 생성된 레지스트리 속성을 식별합니다.
            /// </summary>
            // TypeRegistrySourceGenerator가 Assembly/AllowMultiple과 positional `(Type, string)` 계약으로 매니페스트를 읽습니다.
            [global::System.Runtime.CompilerServices.CompilerGenerated]
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
            sealed class TypeRegistryManifestAttribute : global::System.Attribute
            {
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public TypeRegistryManifestAttribute(global::System.Type ownerType, string propertyName)
                {
                    this.ownerType = ownerType;
                    this.propertyName = propertyName;
                }

                /// <summary>
                /// Gets the type that declares the registry property.<br/>
                /// 레지스트리 속성을 선언한 타입을 가져옵니다.
                /// </summary>
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public global::System.Type ownerType { get; }

                /// <summary>
                /// Gets the name of the registry property.<br/>
                /// 레지스트리 속성의 이름을 가져옵니다.
                /// </summary>
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                public string propertyName { get; }
            }
        }
        """;

    /// <summary>
    /// Adds the generated <c>TypeRegistryManifestAttribute</c> definition to the compilation.<br/>
    /// 생성된 <c>TypeRegistryManifestAttribute</c> 정의를 컴파일에 추가합니다.
    /// </summary>
    /// <param name="context">
    /// The incremental generator initialization context receiving the post-initialization output callback.<br/>
    /// 초기화 후 출력 콜백을 받을 증분 생성기 초기화 컨텍스트입니다.
    /// </param>
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(static context => context.AddSource("RuniOS.Reflection.GenerateTypeRegistryAttribute.g.cs", source));
}
