// Generated by Tmds.DBus.Tool v0.95.1 with arguments: codegen --protocol-api --namespace RuniOS.IO.Locations.Linux.DBus --output UDisks2.g.cs UDisks2.xml
// <auto-generated/>
#nullable enable
namespace RuniOS.IO.Locations.Linux.DBus
{
    sealed partial class ObjectManager : global::Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.freedesktop.DBus.ObjectManager";
        public ObjectManager(global::Tmds.DBus.Protocol.DBusConnection connection, string destination, global::Tmds.DBus.Protocol.ObjectPath path)
            : base(connection, destination, path)
        { }
        public global::System.Threading.Tasks.Task<global::System.Collections.Generic.Dictionary<global::Tmds.DBus.Protocol.ObjectPath, global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.Dictionary<string, global::Tmds.DBus.Protocol.VariantValue>>>> GetManagedObjectsAsync()
        {
            return Connection.CallMethodAsync(CreateMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_aeoaesaesv(m), this);
            global::Tmds.DBus.Protocol.MessageBuffer CreateMessage()
            {
                var writer = Connection.GetMessageWriter();
                writer.WriteMethodCallHeader(
                    destination: Destination,
                    path: Path,
                    @interface: DBusInterfaceName,
                    member: "GetManagedObjects");
                return writer.CreateMessage();
            }
        }
    }
    enum FilesystemProperty
    {
        UnknownProperty = 0,
        MountPoints = 1
    }
    interface IFilesystemProperties
    {
        byte[][] MountPoints { get; }
    }
    interface INullableFilesystemProperties
    {
        byte[][]? MountPoints { get; }
        bool AreAllPropertiesSet();
        FilesystemProperties EnsureAllPropertiesSet();
    }
    interface IChangedFilesystemProperties : INullableFilesystemProperties
    {
        bool HasMountPointsChanged { get; }
    }
    sealed class FilesystemProperties : IChangedFilesystemProperties, IFilesystemProperties
    {
        private uint __set;
        private uint __invalidated;
        private const uint PropertiesAllSet = 0x1U; // 1 properties
        private static uint Flag(FilesystemProperty property) => property == 0 ? 0 : 1U << ((int)property - 1);
        public FilesystemProperties() { }
        #nullable disable
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
        private FilesystemProperties(bool _) { }
        #nullable enable
        private void EnsureSet(FilesystemProperty property)
        {
            if (!HasFlag(__set, property))
            {
                throw new global::System.InvalidOperationException("Property is not set.");
            }
        }
        private byte[][] _mountPoints = default!;
        public required byte[][] MountPoints
        {
            get { EnsureSet(FilesystemProperty.MountPoints); return _mountPoints; }
            set { _mountPoints = value; __set |= Flag(FilesystemProperty.MountPoints); }
        }
        byte[][]? INullableFilesystemProperties.MountPoints
            => IsSet(FilesystemProperty.MountPoints) ? _mountPoints : default(byte[][]?);
        bool IChangedFilesystemProperties.HasMountPointsChanged
            => IsSet(FilesystemProperty.MountPoints) || IsInvalidated(FilesystemProperty.MountPoints);
        FilesystemProperties INullableFilesystemProperties.EnsureAllPropertiesSet()
        {
            EnsureAllPropertiesSet();
            return this;
        }
        public static FilesystemProperties CreateUninitialized() => new FilesystemProperties(false);
        private bool HasFlag(uint flags, FilesystemProperty property)
            => property != 0 && (flags & Flag(property)) != 0;
        public bool IsSet(FilesystemProperty property) => HasFlag(__set, property);
        public bool IsInvalidated(FilesystemProperty property) => HasFlag(__invalidated, property);
        public void SetInvalidated(FilesystemProperty property)
        {
            if (property != 0)
            {
                __invalidated |= Flag(property);
            }
        }
        public bool AreAllPropertiesSet() => __set == PropertiesAllSet;
        public void EnsureAllPropertiesSet()
        {
            if (!AreAllPropertiesSet())
            {
                throw new global::Tmds.DBus.Protocol.DBusUnexpectedValueException($"Not all properties have been set (0x{__set:x}).");
            }
        }
        public static FilesystemProperties ReadFrom(ref global::Tmds.DBus.Protocol.Reader reader, bool withInvalidated)
        {
            var props = CreateUninitialized();
            global::Tmds.DBus.Protocol.ArrayEnd arrayEnd = reader.ReadArrayStart(global::Tmds.DBus.Protocol.DBusType.Struct);
            while (reader.HasNext(arrayEnd))
            {
                var property = reader.ReadString();
                switch (property)
                {
                    case "MountPoints":
                        reader.ReadSignature("aay"u8);
                        props.MountPoints = reader.Read_aay();
                        break;
                    default:
                        reader.ReadVariantValue();
                        break;
                }
            }
            if (withInvalidated)
            {
                global::Tmds.DBus.Protocol.ArrayEnd invalidatedEnd = reader.ReadArrayStart(global::Tmds.DBus.Protocol.DBusType.String);
                while (reader.HasNext(invalidatedEnd))
                {
                    var propertyName = reader.ReadString();
                    props.__invalidated |= propertyName switch
                    {
                        "MountPoints" => Flag(FilesystemProperty.MountPoints),
                        _ => 0
                    };
                }
            }
            return props;
        }
    }
    sealed partial class Filesystem : global::Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.freedesktop.UDisks2.Filesystem";
        public Filesystem(global::Tmds.DBus.Protocol.DBusConnection connection, string destination, global::Tmds.DBus.Protocol.ObjectPath path)
            : base(connection, destination, path)
        { }
        public global::System.Threading.Tasks.Task<byte[][]> GetMountPointsAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("MountPoints"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_aay(m), this);
        public global::System.Threading.Tasks.Task<FilesystemProperties> GetPropertiesAsync()
        {
            return Connection.CallMethodAsync(CreateGetAllPropertiesMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), this);
            static FilesystemProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                return FilesystemProperties.ReadFrom(ref reader, withInvalidated: false);
            }
        }
        public global::System.Threading.Tasks.Task<INullableFilesystemProperties> GetNullablePropertiesAsync()
        {
            return Connection.CallMethodAsync(CreateGetAllPropertiesMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), this);
            static INullableFilesystemProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                return FilesystemProperties.ReadFrom(ref reader, withInvalidated: false);
            }
        }
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Action<IChangedFilesystemProperties> handler, bool emitOnCapturedContext = true)
            => WatchPropertiesChangedAsync(static (global::Tmds.DBus.Protocol.Notification<IChangedFilesystemProperties> n) => ((global::System.Action<IChangedFilesystemProperties>)n.State!)(n.Value), global::Tmds.DBus.Protocol.ObserverFlags.None, emitOnCapturedContext, handler);
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Func<IChangedFilesystemProperties, global::System.Threading.Tasks.ValueTask> handler, bool emitOnCapturedContext = true)
            => WatchPropertiesChangedAsync(static (global::Tmds.DBus.Protocol.Notification<IChangedFilesystemProperties> n) => ((global::System.Func<IChangedFilesystemProperties, global::System.Threading.Tasks.ValueTask>)n.State!)(n.Value), global::Tmds.DBus.Protocol.ObserverFlags.None, emitOnCapturedContext, handler);
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Action<global::Tmds.DBus.Protocol.Notification<IChangedFilesystemProperties>> handler, global::Tmds.DBus.Protocol.ObserverFlags flags, bool emitOnCapturedContext = true, object? state = null)
        {
            return Connection.WatchPropertiesChangedAsync(Destination, Path, DBusInterfaceName, (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), handler, flags, emitOnCapturedContext, state);
            static IChangedFilesystemProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                reader.ReadString(); // interface
                return FilesystemProperties.ReadFrom(ref reader, withInvalidated: true);
            }
        }
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Func<global::Tmds.DBus.Protocol.Notification<IChangedFilesystemProperties>, global::System.Threading.Tasks.ValueTask> handler, global::Tmds.DBus.Protocol.ObserverFlags flags, bool emitOnCapturedContext = true, object? state = null)
        {
            return Connection.WatchPropertiesChangedAsync(Destination, Path, DBusInterfaceName, (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), handler, flags, emitOnCapturedContext, state);
            static IChangedFilesystemProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                reader.ReadString(); // interface
                return FilesystemProperties.ReadFrom(ref reader, withInvalidated: true);
            }
        }
        private global::Tmds.DBus.Protocol.MessageBuffer CreateGetPropertyMessage(string property)
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "ss",
                member: "Get");
            writer.WriteString(DBusInterfaceName);
            writer.WriteString(property);
            return writer.CreateMessage();
        }
        private global::Tmds.DBus.Protocol.MessageBuffer CreateGetAllPropertiesMessage()
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "s",
                member: "GetAll");
            writer.WriteString(DBusInterfaceName);
            return writer.CreateMessage();
        }
    }
    enum BlockProperty
    {
        UnknownProperty = 0,
        Drive = 1,
        Id = 2,
        IdLabel = 3,
        HintName = 4,
        HintIgnore = 5,
        HintIconName = 6,
        HintSymbolicIconName = 7
    }
    interface IBlockProperties
    {
        global::Tmds.DBus.Protocol.ObjectPath Drive { get; }
        string Id { get; }
        string IdLabel { get; }
        string HintName { get; }
        bool HintIgnore { get; }
        string HintIconName { get; }
        string HintSymbolicIconName { get; }
    }
    interface INullableBlockProperties
    {
        global::Tmds.DBus.Protocol.ObjectPath? Drive { get; }
        string? Id { get; }
        string? IdLabel { get; }
        string? HintName { get; }
        bool? HintIgnore { get; }
        string? HintIconName { get; }
        string? HintSymbolicIconName { get; }
        bool AreAllPropertiesSet();
        BlockProperties EnsureAllPropertiesSet();
    }
    interface IChangedBlockProperties : INullableBlockProperties
    {
        bool HasDriveChanged { get; }
        bool HasIdChanged { get; }
        bool HasIdLabelChanged { get; }
        bool HasHintNameChanged { get; }
        bool HasHintIgnoreChanged { get; }
        bool HasHintIconNameChanged { get; }
        bool HasHintSymbolicIconNameChanged { get; }
    }
    sealed class BlockProperties : IChangedBlockProperties, IBlockProperties
    {
        private uint __set;
        private uint __invalidated;
        private const uint PropertiesAllSet = 0x7FU; // 7 properties
        private static uint Flag(BlockProperty property) => property == 0 ? 0 : 1U << ((int)property - 1);
        public BlockProperties() { }
        #nullable disable
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
        private BlockProperties(bool _) { }
        #nullable enable
        private void EnsureSet(BlockProperty property)
        {
            if (!HasFlag(__set, property))
            {
                throw new global::System.InvalidOperationException("Property is not set.");
            }
        }
        private global::Tmds.DBus.Protocol.ObjectPath _drive = default!;
        public required global::Tmds.DBus.Protocol.ObjectPath Drive
        {
            get { EnsureSet(BlockProperty.Drive); return _drive; }
            set { _drive = value; __set |= Flag(BlockProperty.Drive); }
        }
        private string _id = default!;
        public required string Id
        {
            get { EnsureSet(BlockProperty.Id); return _id; }
            set { _id = value; __set |= Flag(BlockProperty.Id); }
        }
        private string _idLabel = default!;
        public required string IdLabel
        {
            get { EnsureSet(BlockProperty.IdLabel); return _idLabel; }
            set { _idLabel = value; __set |= Flag(BlockProperty.IdLabel); }
        }
        private string _hintName = default!;
        public required string HintName
        {
            get { EnsureSet(BlockProperty.HintName); return _hintName; }
            set { _hintName = value; __set |= Flag(BlockProperty.HintName); }
        }
        private bool _hintIgnore = default!;
        public required bool HintIgnore
        {
            get { EnsureSet(BlockProperty.HintIgnore); return _hintIgnore; }
            set { _hintIgnore = value; __set |= Flag(BlockProperty.HintIgnore); }
        }
        private string _hintIconName = default!;
        public required string HintIconName
        {
            get { EnsureSet(BlockProperty.HintIconName); return _hintIconName; }
            set { _hintIconName = value; __set |= Flag(BlockProperty.HintIconName); }
        }
        private string _hintSymbolicIconName = default!;
        public required string HintSymbolicIconName
        {
            get { EnsureSet(BlockProperty.HintSymbolicIconName); return _hintSymbolicIconName; }
            set { _hintSymbolicIconName = value; __set |= Flag(BlockProperty.HintSymbolicIconName); }
        }
        global::Tmds.DBus.Protocol.ObjectPath? INullableBlockProperties.Drive
            => IsSet(BlockProperty.Drive) ? _drive : default(global::Tmds.DBus.Protocol.ObjectPath?);
        string? INullableBlockProperties.Id
            => IsSet(BlockProperty.Id) ? _id : default(string?);
        string? INullableBlockProperties.IdLabel
            => IsSet(BlockProperty.IdLabel) ? _idLabel : default(string?);
        string? INullableBlockProperties.HintName
            => IsSet(BlockProperty.HintName) ? _hintName : default(string?);
        bool? INullableBlockProperties.HintIgnore
            => IsSet(BlockProperty.HintIgnore) ? _hintIgnore : default(bool?);
        string? INullableBlockProperties.HintIconName
            => IsSet(BlockProperty.HintIconName) ? _hintIconName : default(string?);
        string? INullableBlockProperties.HintSymbolicIconName
            => IsSet(BlockProperty.HintSymbolicIconName) ? _hintSymbolicIconName : default(string?);
        bool IChangedBlockProperties.HasDriveChanged
            => IsSet(BlockProperty.Drive) || IsInvalidated(BlockProperty.Drive);
        bool IChangedBlockProperties.HasIdChanged
            => IsSet(BlockProperty.Id) || IsInvalidated(BlockProperty.Id);
        bool IChangedBlockProperties.HasIdLabelChanged
            => IsSet(BlockProperty.IdLabel) || IsInvalidated(BlockProperty.IdLabel);
        bool IChangedBlockProperties.HasHintNameChanged
            => IsSet(BlockProperty.HintName) || IsInvalidated(BlockProperty.HintName);
        bool IChangedBlockProperties.HasHintIgnoreChanged
            => IsSet(BlockProperty.HintIgnore) || IsInvalidated(BlockProperty.HintIgnore);
        bool IChangedBlockProperties.HasHintIconNameChanged
            => IsSet(BlockProperty.HintIconName) || IsInvalidated(BlockProperty.HintIconName);
        bool IChangedBlockProperties.HasHintSymbolicIconNameChanged
            => IsSet(BlockProperty.HintSymbolicIconName) || IsInvalidated(BlockProperty.HintSymbolicIconName);
        BlockProperties INullableBlockProperties.EnsureAllPropertiesSet()
        {
            EnsureAllPropertiesSet();
            return this;
        }
        public static BlockProperties CreateUninitialized() => new BlockProperties(false);
        private bool HasFlag(uint flags, BlockProperty property)
            => property != 0 && (flags & Flag(property)) != 0;
        public bool IsSet(BlockProperty property) => HasFlag(__set, property);
        public bool IsInvalidated(BlockProperty property) => HasFlag(__invalidated, property);
        public void SetInvalidated(BlockProperty property)
        {
            if (property != 0)
            {
                __invalidated |= Flag(property);
            }
        }
        public bool AreAllPropertiesSet() => __set == PropertiesAllSet;
        public void EnsureAllPropertiesSet()
        {
            if (!AreAllPropertiesSet())
            {
                throw new global::Tmds.DBus.Protocol.DBusUnexpectedValueException($"Not all properties have been set (0x{__set:x}).");
            }
        }
        public static BlockProperties ReadFrom(ref global::Tmds.DBus.Protocol.Reader reader, bool withInvalidated)
        {
            var props = CreateUninitialized();
            global::Tmds.DBus.Protocol.ArrayEnd arrayEnd = reader.ReadArrayStart(global::Tmds.DBus.Protocol.DBusType.Struct);
            while (reader.HasNext(arrayEnd))
            {
                var property = reader.ReadString();
                switch (property)
                {
                    case "Drive":
                        reader.ReadSignature("o"u8);
                        props.Drive = reader.ReadObjectPath();
                        break;
                    case "Id":
                        reader.ReadSignature("s"u8);
                        props.Id = reader.ReadString();
                        break;
                    case "IdLabel":
                        reader.ReadSignature("s"u8);
                        props.IdLabel = reader.ReadString();
                        break;
                    case "HintName":
                        reader.ReadSignature("s"u8);
                        props.HintName = reader.ReadString();
                        break;
                    case "HintIgnore":
                        reader.ReadSignature("b"u8);
                        props.HintIgnore = reader.ReadBool();
                        break;
                    case "HintIconName":
                        reader.ReadSignature("s"u8);
                        props.HintIconName = reader.ReadString();
                        break;
                    case "HintSymbolicIconName":
                        reader.ReadSignature("s"u8);
                        props.HintSymbolicIconName = reader.ReadString();
                        break;
                    default:
                        reader.ReadVariantValue();
                        break;
                }
            }
            if (withInvalidated)
            {
                global::Tmds.DBus.Protocol.ArrayEnd invalidatedEnd = reader.ReadArrayStart(global::Tmds.DBus.Protocol.DBusType.String);
                while (reader.HasNext(invalidatedEnd))
                {
                    var propertyName = reader.ReadString();
                    props.__invalidated |= propertyName switch
                    {
                        "Drive" => Flag(BlockProperty.Drive),
                        "Id" => Flag(BlockProperty.Id),
                        "IdLabel" => Flag(BlockProperty.IdLabel),
                        "HintName" => Flag(BlockProperty.HintName),
                        "HintIgnore" => Flag(BlockProperty.HintIgnore),
                        "HintIconName" => Flag(BlockProperty.HintIconName),
                        "HintSymbolicIconName" => Flag(BlockProperty.HintSymbolicIconName),
                        _ => 0
                    };
                }
            }
            return props;
        }
    }
    sealed partial class Block : global::Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.freedesktop.UDisks2.Block";
        public Block(global::Tmds.DBus.Protocol.DBusConnection connection, string destination, global::Tmds.DBus.Protocol.ObjectPath path)
            : base(connection, destination, path)
        { }
        public global::System.Threading.Tasks.Task<global::Tmds.DBus.Protocol.ObjectPath> GetDriveAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("Drive"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_o(m), this);
        public global::System.Threading.Tasks.Task<string> GetIdAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("Id"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_s(m), this);
        public global::System.Threading.Tasks.Task<string> GetIdLabelAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("IdLabel"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_s(m), this);
        public global::System.Threading.Tasks.Task<string> GetHintNameAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("HintName"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_s(m), this);
        public global::System.Threading.Tasks.Task<bool> GetHintIgnoreAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("HintIgnore"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_b(m), this);
        public global::System.Threading.Tasks.Task<string> GetHintIconNameAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("HintIconName"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_s(m), this);
        public global::System.Threading.Tasks.Task<string> GetHintSymbolicIconNameAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("HintSymbolicIconName"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_s(m), this);
        public global::System.Threading.Tasks.Task<BlockProperties> GetPropertiesAsync()
        {
            return Connection.CallMethodAsync(CreateGetAllPropertiesMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), this);
            static BlockProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                return BlockProperties.ReadFrom(ref reader, withInvalidated: false);
            }
        }
        public global::System.Threading.Tasks.Task<INullableBlockProperties> GetNullablePropertiesAsync()
        {
            return Connection.CallMethodAsync(CreateGetAllPropertiesMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), this);
            static INullableBlockProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                return BlockProperties.ReadFrom(ref reader, withInvalidated: false);
            }
        }
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Action<IChangedBlockProperties> handler, bool emitOnCapturedContext = true)
            => WatchPropertiesChangedAsync(static (global::Tmds.DBus.Protocol.Notification<IChangedBlockProperties> n) => ((global::System.Action<IChangedBlockProperties>)n.State!)(n.Value), global::Tmds.DBus.Protocol.ObserverFlags.None, emitOnCapturedContext, handler);
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Func<IChangedBlockProperties, global::System.Threading.Tasks.ValueTask> handler, bool emitOnCapturedContext = true)
            => WatchPropertiesChangedAsync(static (global::Tmds.DBus.Protocol.Notification<IChangedBlockProperties> n) => ((global::System.Func<IChangedBlockProperties, global::System.Threading.Tasks.ValueTask>)n.State!)(n.Value), global::Tmds.DBus.Protocol.ObserverFlags.None, emitOnCapturedContext, handler);
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Action<global::Tmds.DBus.Protocol.Notification<IChangedBlockProperties>> handler, global::Tmds.DBus.Protocol.ObserverFlags flags, bool emitOnCapturedContext = true, object? state = null)
        {
            return Connection.WatchPropertiesChangedAsync(Destination, Path, DBusInterfaceName, (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), handler, flags, emitOnCapturedContext, state);
            static IChangedBlockProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                reader.ReadString(); // interface
                return BlockProperties.ReadFrom(ref reader, withInvalidated: true);
            }
        }
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Func<global::Tmds.DBus.Protocol.Notification<IChangedBlockProperties>, global::System.Threading.Tasks.ValueTask> handler, global::Tmds.DBus.Protocol.ObserverFlags flags, bool emitOnCapturedContext = true, object? state = null)
        {
            return Connection.WatchPropertiesChangedAsync(Destination, Path, DBusInterfaceName, (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), handler, flags, emitOnCapturedContext, state);
            static IChangedBlockProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                reader.ReadString(); // interface
                return BlockProperties.ReadFrom(ref reader, withInvalidated: true);
            }
        }
        private global::Tmds.DBus.Protocol.MessageBuffer CreateGetPropertyMessage(string property)
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "ss",
                member: "Get");
            writer.WriteString(DBusInterfaceName);
            writer.WriteString(property);
            return writer.CreateMessage();
        }
        private global::Tmds.DBus.Protocol.MessageBuffer CreateGetAllPropertiesMessage()
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "s",
                member: "GetAll");
            writer.WriteString(DBusInterfaceName);
            return writer.CreateMessage();
        }
    }
    enum DriveProperty
    {
        UnknownProperty = 0,
        Vendor = 1,
        Model = 2,
        Removable = 3,
        Optical = 4,
        ConnectionBus = 5
    }
    interface IDriveProperties
    {
        string Vendor { get; }
        string Model { get; }
        bool Removable { get; }
        bool Optical { get; }
        string ConnectionBus { get; }
    }
    interface INullableDriveProperties
    {
        string? Vendor { get; }
        string? Model { get; }
        bool? Removable { get; }
        bool? Optical { get; }
        string? ConnectionBus { get; }
        bool AreAllPropertiesSet();
        DriveProperties EnsureAllPropertiesSet();
    }
    interface IChangedDriveProperties : INullableDriveProperties
    {
        bool HasVendorChanged { get; }
        bool HasModelChanged { get; }
        bool HasRemovableChanged { get; }
        bool HasOpticalChanged { get; }
        bool HasConnectionBusChanged { get; }
    }
    sealed class DriveProperties : IChangedDriveProperties, IDriveProperties
    {
        private uint __set;
        private uint __invalidated;
        private const uint PropertiesAllSet = 0x1FU; // 5 properties
        private static uint Flag(DriveProperty property) => property == 0 ? 0 : 1U << ((int)property - 1);
        public DriveProperties() { }
        #nullable disable
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
        private DriveProperties(bool _) { }
        #nullable enable
        private void EnsureSet(DriveProperty property)
        {
            if (!HasFlag(__set, property))
            {
                throw new global::System.InvalidOperationException("Property is not set.");
            }
        }
        private string _vendor = default!;
        public required string Vendor
        {
            get { EnsureSet(DriveProperty.Vendor); return _vendor; }
            set { _vendor = value; __set |= Flag(DriveProperty.Vendor); }
        }
        private string _model = default!;
        public required string Model
        {
            get { EnsureSet(DriveProperty.Model); return _model; }
            set { _model = value; __set |= Flag(DriveProperty.Model); }
        }
        private bool _removable = default!;
        public required bool Removable
        {
            get { EnsureSet(DriveProperty.Removable); return _removable; }
            set { _removable = value; __set |= Flag(DriveProperty.Removable); }
        }
        private bool _optical = default!;
        public required bool Optical
        {
            get { EnsureSet(DriveProperty.Optical); return _optical; }
            set { _optical = value; __set |= Flag(DriveProperty.Optical); }
        }
        private string _connectionBus = default!;
        public required string ConnectionBus
        {
            get { EnsureSet(DriveProperty.ConnectionBus); return _connectionBus; }
            set { _connectionBus = value; __set |= Flag(DriveProperty.ConnectionBus); }
        }
        string? INullableDriveProperties.Vendor
            => IsSet(DriveProperty.Vendor) ? _vendor : default(string?);
        string? INullableDriveProperties.Model
            => IsSet(DriveProperty.Model) ? _model : default(string?);
        bool? INullableDriveProperties.Removable
            => IsSet(DriveProperty.Removable) ? _removable : default(bool?);
        bool? INullableDriveProperties.Optical
            => IsSet(DriveProperty.Optical) ? _optical : default(bool?);
        string? INullableDriveProperties.ConnectionBus
            => IsSet(DriveProperty.ConnectionBus) ? _connectionBus : default(string?);
        bool IChangedDriveProperties.HasVendorChanged
            => IsSet(DriveProperty.Vendor) || IsInvalidated(DriveProperty.Vendor);
        bool IChangedDriveProperties.HasModelChanged
            => IsSet(DriveProperty.Model) || IsInvalidated(DriveProperty.Model);
        bool IChangedDriveProperties.HasRemovableChanged
            => IsSet(DriveProperty.Removable) || IsInvalidated(DriveProperty.Removable);
        bool IChangedDriveProperties.HasOpticalChanged
            => IsSet(DriveProperty.Optical) || IsInvalidated(DriveProperty.Optical);
        bool IChangedDriveProperties.HasConnectionBusChanged
            => IsSet(DriveProperty.ConnectionBus) || IsInvalidated(DriveProperty.ConnectionBus);
        DriveProperties INullableDriveProperties.EnsureAllPropertiesSet()
        {
            EnsureAllPropertiesSet();
            return this;
        }
        public static DriveProperties CreateUninitialized() => new DriveProperties(false);
        private bool HasFlag(uint flags, DriveProperty property)
            => property != 0 && (flags & Flag(property)) != 0;
        public bool IsSet(DriveProperty property) => HasFlag(__set, property);
        public bool IsInvalidated(DriveProperty property) => HasFlag(__invalidated, property);
        public void SetInvalidated(DriveProperty property)
        {
            if (property != 0)
            {
                __invalidated |= Flag(property);
            }
        }
        public bool AreAllPropertiesSet() => __set == PropertiesAllSet;
        public void EnsureAllPropertiesSet()
        {
            if (!AreAllPropertiesSet())
            {
                throw new global::Tmds.DBus.Protocol.DBusUnexpectedValueException($"Not all properties have been set (0x{__set:x}).");
            }
        }
        public static DriveProperties ReadFrom(ref global::Tmds.DBus.Protocol.Reader reader, bool withInvalidated)
        {
            var props = CreateUninitialized();
            global::Tmds.DBus.Protocol.ArrayEnd arrayEnd = reader.ReadArrayStart(global::Tmds.DBus.Protocol.DBusType.Struct);
            while (reader.HasNext(arrayEnd))
            {
                var property = reader.ReadString();
                switch (property)
                {
                    case "Vendor":
                        reader.ReadSignature("s"u8);
                        props.Vendor = reader.ReadString();
                        break;
                    case "Model":
                        reader.ReadSignature("s"u8);
                        props.Model = reader.ReadString();
                        break;
                    case "Removable":
                        reader.ReadSignature("b"u8);
                        props.Removable = reader.ReadBool();
                        break;
                    case "Optical":
                        reader.ReadSignature("b"u8);
                        props.Optical = reader.ReadBool();
                        break;
                    case "ConnectionBus":
                        reader.ReadSignature("s"u8);
                        props.ConnectionBus = reader.ReadString();
                        break;
                    default:
                        reader.ReadVariantValue();
                        break;
                }
            }
            if (withInvalidated)
            {
                global::Tmds.DBus.Protocol.ArrayEnd invalidatedEnd = reader.ReadArrayStart(global::Tmds.DBus.Protocol.DBusType.String);
                while (reader.HasNext(invalidatedEnd))
                {
                    var propertyName = reader.ReadString();
                    props.__invalidated |= propertyName switch
                    {
                        "Vendor" => Flag(DriveProperty.Vendor),
                        "Model" => Flag(DriveProperty.Model),
                        "Removable" => Flag(DriveProperty.Removable),
                        "Optical" => Flag(DriveProperty.Optical),
                        "ConnectionBus" => Flag(DriveProperty.ConnectionBus),
                        _ => 0
                    };
                }
            }
            return props;
        }
    }
    sealed partial class Drive : global::Tmds.DBus.Protocol.DBusObject
    {
        public const string DBusInterfaceName = "org.freedesktop.UDisks2.Drive";
        public Drive(global::Tmds.DBus.Protocol.DBusConnection connection, string destination, global::Tmds.DBus.Protocol.ObjectPath path)
            : base(connection, destination, path)
        { }
        public global::System.Threading.Tasks.Task<string> GetVendorAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("Vendor"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_s(m), this);
        public global::System.Threading.Tasks.Task<string> GetModelAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("Model"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_s(m), this);
        public global::System.Threading.Tasks.Task<bool> GetRemovableAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("Removable"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_b(m), this);
        public global::System.Threading.Tasks.Task<bool> GetOpticalAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("Optical"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_b(m), this);
        public global::System.Threading.Tasks.Task<string> GetConnectionBusAsync()
            => Connection.CallMethodAsync(CreateGetPropertyMessage("ConnectionBus"), (global::Tmds.DBus.Protocol.Message m, object? s) => MessageReader.Read_v_s(m), this);
        public global::System.Threading.Tasks.Task<DriveProperties> GetPropertiesAsync()
        {
            return Connection.CallMethodAsync(CreateGetAllPropertiesMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), this);
            static DriveProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                return DriveProperties.ReadFrom(ref reader, withInvalidated: false);
            }
        }
        public global::System.Threading.Tasks.Task<INullableDriveProperties> GetNullablePropertiesAsync()
        {
            return Connection.CallMethodAsync(CreateGetAllPropertiesMessage(), (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), this);
            static INullableDriveProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                return DriveProperties.ReadFrom(ref reader, withInvalidated: false);
            }
        }
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Action<IChangedDriveProperties> handler, bool emitOnCapturedContext = true)
            => WatchPropertiesChangedAsync(static (global::Tmds.DBus.Protocol.Notification<IChangedDriveProperties> n) => ((global::System.Action<IChangedDriveProperties>)n.State!)(n.Value), global::Tmds.DBus.Protocol.ObserverFlags.None, emitOnCapturedContext, handler);
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Func<IChangedDriveProperties, global::System.Threading.Tasks.ValueTask> handler, bool emitOnCapturedContext = true)
            => WatchPropertiesChangedAsync(static (global::Tmds.DBus.Protocol.Notification<IChangedDriveProperties> n) => ((global::System.Func<IChangedDriveProperties, global::System.Threading.Tasks.ValueTask>)n.State!)(n.Value), global::Tmds.DBus.Protocol.ObserverFlags.None, emitOnCapturedContext, handler);
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Action<global::Tmds.DBus.Protocol.Notification<IChangedDriveProperties>> handler, global::Tmds.DBus.Protocol.ObserverFlags flags, bool emitOnCapturedContext = true, object? state = null)
        {
            return Connection.WatchPropertiesChangedAsync(Destination, Path, DBusInterfaceName, (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), handler, flags, emitOnCapturedContext, state);
            static IChangedDriveProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                reader.ReadString(); // interface
                return DriveProperties.ReadFrom(ref reader, withInvalidated: true);
            }
        }
        public global::System.Threading.Tasks.ValueTask<global::System.IDisposable> WatchPropertiesChangedAsync(global::System.Func<global::Tmds.DBus.Protocol.Notification<IChangedDriveProperties>, global::System.Threading.Tasks.ValueTask> handler, global::Tmds.DBus.Protocol.ObserverFlags flags, bool emitOnCapturedContext = true, object? state = null)
        {
            return Connection.WatchPropertiesChangedAsync(Destination, Path, DBusInterfaceName, (global::Tmds.DBus.Protocol.Message m, object? s) => ReadMessage(m), handler, flags, emitOnCapturedContext, state);
            static IChangedDriveProperties ReadMessage(global::Tmds.DBus.Protocol.Message message)
            {
                var reader = message.GetBodyReader();
                reader.ReadString(); // interface
                return DriveProperties.ReadFrom(ref reader, withInvalidated: true);
            }
        }
        private global::Tmds.DBus.Protocol.MessageBuffer CreateGetPropertyMessage(string property)
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "ss",
                member: "Get");
            writer.WriteString(DBusInterfaceName);
            writer.WriteString(property);
            return writer.CreateMessage();
        }
        private global::Tmds.DBus.Protocol.MessageBuffer CreateGetAllPropertiesMessage()
        {
            var writer = Connection.GetMessageWriter();
            writer.WriteMethodCallHeader(
                destination: Destination,
                path: Path,
                @interface: "org.freedesktop.DBus.Properties",
                signature: "s",
                member: "GetAll");
            writer.WriteString(DBusInterfaceName);
            return writer.CreateMessage();
        }
    }
    static partial class ObjectFactory
    {
        public static ObjectManager CreateObjectManager(this global::Tmds.DBus.Protocol.DBusService service, global::Tmds.DBus.Protocol.ObjectPath path) => new ObjectManager(service.Connection, service.Name, path);
        public static Filesystem CreateFilesystem(this global::Tmds.DBus.Protocol.DBusService service, global::Tmds.DBus.Protocol.ObjectPath path) => new Filesystem(service.Connection, service.Name, path);
        public static Block CreateBlock(this global::Tmds.DBus.Protocol.DBusService service, global::Tmds.DBus.Protocol.ObjectPath path) => new Block(service.Connection, service.Name, path);
        public static Drive CreateDrive(this global::Tmds.DBus.Protocol.DBusService service, global::Tmds.DBus.Protocol.ObjectPath path) => new Drive(service.Connection, service.Name, path);
    }
    file static class MessageReader
    {
        public static global::System.Collections.Generic.Dictionary<global::Tmds.DBus.Protocol.ObjectPath, global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.Dictionary<string, global::Tmds.DBus.Protocol.VariantValue>>> Read_aeoaesaesv(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            return reader.Read_aeoaesaesv();
        }
        public static byte[][] Read_v_aay(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            reader.ReadSignature("aay"u8);
            return reader.Read_aay();
        }
        public static global::Tmds.DBus.Protocol.ObjectPath Read_v_o(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            reader.ReadSignature("o"u8);
            return reader.ReadObjectPath();
        }
        public static string Read_v_s(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            reader.ReadSignature("s"u8);
            return reader.ReadString();
        }
        public static bool Read_v_b(global::Tmds.DBus.Protocol.Message message)
        {
            var reader = message.GetBodyReader();
            reader.ReadSignature("b"u8);
            return reader.ReadBool();
        }
        public static byte[][] Read_aay(this ref global::Tmds.DBus.Protocol.Reader reader)
        {
            global::System.Collections.Generic.List<byte[]> list = new();
            global::Tmds.DBus.Protocol.ArrayEnd arrayEnd = reader.ReadArrayStart(global::Tmds.DBus.Protocol.DBusType.Array);
            while (reader.HasNext(arrayEnd))
            {
                list.Add(reader.ReadArrayOfByte());
            }
            return list.ToArray();
        }
        public static global::System.Collections.Generic.Dictionary<global::Tmds.DBus.Protocol.ObjectPath, global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.Dictionary<string, global::Tmds.DBus.Protocol.VariantValue>>> Read_aeoaesaesv(this ref global::Tmds.DBus.Protocol.Reader reader)
        {
            global::System.Collections.Generic.Dictionary<global::Tmds.DBus.Protocol.ObjectPath, global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.Dictionary<string, global::Tmds.DBus.Protocol.VariantValue>>> dictionary = new();
            global::Tmds.DBus.Protocol.ArrayEnd dictEnd = reader.ReadDictionaryStart();
            while (reader.HasNext(dictEnd))
            {
                var key = reader.ReadObjectPath();
                var value = reader.Read_aesaesv();
                dictionary[key] = value;
            }
            return dictionary;
        }
        public static global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.Dictionary<string, global::Tmds.DBus.Protocol.VariantValue>> Read_aesaesv(this ref global::Tmds.DBus.Protocol.Reader reader)
        {
            global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.Dictionary<string, global::Tmds.DBus.Protocol.VariantValue>> dictionary = new();
            global::Tmds.DBus.Protocol.ArrayEnd dictEnd = reader.ReadDictionaryStart();
            while (reader.HasNext(dictEnd))
            {
                var key = reader.ReadString();
                var value = reader.ReadDictionaryOfStringToVariantValue();
                dictionary[key] = value;
            }
            return dictionary;
        }
    }
    file static class MessageWriterExtensions
    {
    }
}
