<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0" PrivateAssets="all" />

        <EmbeddedResource Update="Diagnostics\SerializerDiagnostics.resx">
            <LogicalName>RuniOS.CodeAnalysis.Diagnostics.Diagnostics.resources</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Update="Diagnostics\SerializerDiagnostics.ko.resx">
            <LogicalName>RuniOS.CodeAnalysis.Diagnostics.Diagnostics.ko.resources</LogicalName>
            <DependentUpon>SerializerDiagnostics.cs</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Diagnostics/TypeRegistryDiagnostics.resx">
            <LogicalName>RuniOS.CodeAnalysis.Diagnostics.TypeRegistryDiagnostics.resources</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Update="Diagnostics/TypeRegistryDiagnostics.ko.resx">
            <LogicalName>RuniOS.CodeAnalysis.Diagnostics.TypeRegistryDiagnostics.ko.resources</LogicalName>
            <DependentUpon>TypeRegistryDiagnostics.cs</DependentUpon>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Generators\LocationDataExtension.cs">
        <DependentUpon>LocationData.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\LocationDataExtension.cs">
        <DependentUpon>LocationData.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\PartialTypeDeclarationsExtensions.cs">
        <DependentUpon>PartialTypeDeclarations.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\PartialTypeDeclarations.cs">
        <DependentUpon>PartialTypeDeclarationsSerializer.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\PartialTypeDeclaration.cs">
        <DependentUpon>PartialTypeDeclarationsSerializer.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\TypeSyntaxSerializer.Array.cs">
        <DependentUpon>TypeSyntaxSerializer.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\TypeSyntaxSerializer.DynamicType.cs">
        <DependentUpon>TypeSyntaxSerializer.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\TypeSyntaxSerializer.FunctionPointer.cs">
        <DependentUpon>TypeSyntaxSerializer.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\TypeSyntaxSerializer.NamedType.cs">
        <DependentUpon>TypeSyntaxSerializer.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\TypeSyntaxSerializer.Pointer.cs">
        <DependentUpon>TypeSyntaxSerializer.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\TypeSyntaxSerializer.TypeParameter.cs">
        <DependentUpon>TypeSyntaxSerializer.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\SourceWriter.Append.cs">
        <DependentUpon>SourceWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\SourceWriter.AppendIdentifier.cs">
        <DependentUpon>SourceWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\SourceWriter.AppendJoin.cs">
        <DependentUpon>SourceWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\SourceWriter.AppendLine.cs">
        <DependentUpon>SourceWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\SourceWriter.Block.cs">
        <DependentUpon>SourceWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\SourceWriter.Indent.cs">
        <DependentUpon>SourceWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\SourceWriter.Namespace.cs">
        <DependentUpon>SourceWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\SourceWriter.AppendLineCompilerGenerated.cs">
        <DependentUpon>SourceWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Generators\SourceWriter.AppendLineEditorBrowsable.cs">
        <DependentUpon>SourceWriter.cs</DependentUpon>
      </Compile>
    </ItemGroup>

    <Target Name="CopyAnalyzerToUnityPackage" AfterTargets="Build">
        <PropertyGroup>
            <UnityAnalyzerDirectory>$(MSBuildThisFileDirectory)../Packages/com.rumi.runios.core/Plugins/RuniOS.CodeAnalysis/</UnityAnalyzerDirectory>
        </PropertyGroup>

        <MakeDir Directories="$(UnityAnalyzerDirectory)" />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(UnityAnalyzerDirectory)" SkipUnchangedFiles="true" />
        <Copy SourceFiles="$(TargetDir)$(AssemblyName).pdb" DestinationFolder="$(UnityAnalyzerDirectory)" Condition="Exists('$(TargetDir)$(AssemblyName).pdb')" SkipUnchangedFiles="true" />

        <ItemGroup>
            <AnalyzerSatelliteFiles Include="$(TargetDir)**\$(AssemblyName).resources.dll" />
        </ItemGroup>
        <MakeDir Directories="@(AnalyzerSatelliteFiles->'$(UnityAnalyzerDirectory)%(RecursiveDir)')" />
        <Copy
            SourceFiles="@(AnalyzerSatelliteFiles)"
            DestinationFiles="@(AnalyzerSatelliteFiles->'$(UnityAnalyzerDirectory)%(RecursiveDir)%(Filename)%(Extension)')"
            SkipUnchangedFiles="true"
        />
    </Target>

</Project>
