using Microsoft.CodeAnalysis;

namespace RuniOS.CodeAnalysis.Generators;

/// <summary>
/// Injects the compiler-recognized attribute definition used to hide embedded implementation types from referenced-assembly lookup.<br/>
/// 참조 어셈블리 조회에서 포함된 구현 타입을 숨기는 데 사용할 컴파일러 인식 특성 정의를 주입합니다.
/// </summary>
[Generator]
public sealed class EmbeddedAttributeSourceGenerator : IIncrementalGenerator
{
    const string source =
        """
        // <auto-generated/>
        // ReSharper disable All
        #nullable enable
        namespace Microsoft.CodeAnalysis
        {
            internal sealed partial class EmbeddedAttribute : global::System.Attribute { }
        }
        """;

    /// <summary>
    /// Adds the generated <c>Microsoft.CodeAnalysis.EmbeddedAttribute</c> definition to the compilation.<br/>
    /// 생성된 <c>Microsoft.CodeAnalysis.EmbeddedAttribute</c> 정의를 컴파일에 추가합니다.
    /// </summary>
    /// <param name="context">
    /// The incremental generator initialization context receiving the post-initialization output callback.<br/>
    /// 초기화 후 출력 콜백을 받을 증분 생성기 초기화 컨텍스트입니다.
    /// </param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Microsoft.CodeAnalysis 4.3에는 AddEmbeddedAttributeDefinition helper가 없으므로 같은 정의를 직접 추가합니다.
        context.RegisterPostInitializationOutput(static context => context.AddSource("Microsoft.CodeAnalysis.EmbeddedAttribute.g.cs", source));
    }
}
