using Microsoft.CodeAnalysis;

namespace RuniOS.CodeAnalysis.Generators;

/// <summary>
/// Injects the internal compiler-recognized module initializer attribute before source generation.<br/>
/// 소스 생성 전에 컴파일러가 인식하는 내부 모듈 초기화자 특성 정의를 주입합니다.
/// </summary>
[Generator]
public sealed class ModuleInitializerAttributeSourceGenerator : IIncrementalGenerator
{
    const string source =
        """
        // <auto-generated/>
        // ReSharper disable All
        #nullable enable
        namespace System.Runtime.CompilerServices
        {
            [global::System.Runtime.CompilerServices.CompilerGenerated]
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
            internal sealed class ModuleInitializerAttribute : global::System.Attribute { }
        }
        """;

    /// <summary>
    /// Adds the internal module initializer attribute definition to the post-initialization compilation.<br/>
    /// 초기화 후 컴파일에 내부 모듈 초기화자 특성 정의를 추가합니다.
    /// </summary>
    /// <param name="context">
    /// The incremental generator initialization context receiving the post-initialization output callback.<br/>
    /// 초기화 후 출력 콜백을 받을 증분 생성기 초기화 컨텍스트입니다.
    /// </param>
    public void Initialize(IncrementalGeneratorInitializationContext context) => context.RegisterPostInitializationOutput(static postInitializationContext => postInitializationContext.AddSource("System.Runtime.CompilerServices.ModuleInitializerAttribute.g.cs", source));
}
