using Microsoft.CodeAnalysis.CSharp;
using System.Text;

namespace RuniOS.CodeAnalysis.Generators;

/// <summary>
/// Builds generated source text one line at a time while tracking indentation.<br/>
/// 들여쓰기를 추적하면서 생성된 소스 텍스트를 한 줄씩 구성합니다.
/// </summary>
public sealed partial class SourceWriter
{
    public SourceWriter()
    {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("// ReSharper disable All");
        builder.AppendLine("#nullable enable");
    }

    public bool isEmpty => builder.Length == 0;
    public bool isLineStart => isEmpty || SyntaxFacts.IsNewLine(builder[^1]);
    public bool isTokenBoundary => isEmpty || SyntaxFacts.IsWhitespace(builder[^1]);

    public bool isBlankLineStart
    {
        get
        {
            int index = builder.Length;
            return ConsumeNewLine(ref index) && ConsumeNewLine(ref index);
        }
    }

    public int indentLevel { get; private set; } = 0;

    readonly StringBuilder builder = new();

    public void EnsureBlankLine()
    {
        if (isEmpty)
            return;

        if (!isLineStart)
            builder.AppendLine();

        if (!isBlankLineStart)
            builder.AppendLine();
    }

    bool ConsumeNewLine(ref int index)
    {
        if (index <= 0)
            return false;

        char ch = builder[index - 1];
        if (!SyntaxFacts.IsNewLine(ch))
            return false;

        index--;

        if (ch == '\n' && index > 0 && builder[index - 1] == '\r')
            index--;

        return true;
    }

    void AppendIndentationIfNeeded()
    {
        if (isLineStart)
            builder.Append(' ', indentLevel * 4);
    }

    /// <summary>
    /// Returns all source text appended to this writer.<br/>
    /// 이 작성기에 추가된 전체 소스 텍스트를 반환합니다.
    /// </summary>
    /// <returns>
    /// The accumulated source text.<br/>
    /// 누적된 소스 텍스트입니다.
    /// </returns>
    public override string ToString() => builder.ToString();
}